<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MarketplaceBetter.Domain\MarketplaceBetter.Domain.csproj" />
    <ProjectReference Include="..\MarketplaceBetter.Infrastructure\MarketplaceBetter.Infrastructure.csproj" />
  </ItemGroup>

</Project>
