CREATE TABLE [dbo].[APlusImage]
(
	[Id]		BIGINT			NOT NULL	IDENTITY,
	[CloudId]	NVARCHAR (255)	NOT NULL,
	[Version]	NVARCHAR (255)	NOT NULL,
	[Url]		NVARCHAR (255)	NOT NULL,
	[FileName]	NVARCHAR (255)	NOT NULL,
	CONSTRAINT	[PK_APlusImage]	PRIMARY KEY ([Id]),
);
GO