<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <StartupObject>MarketplaceBetter.Web.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <_WebToolingArtifacts Remove="Properties\PublishProfiles\Test_PublishProfile.pubxml" />
    <_WebToolingArtifacts Remove="Properties\PublishProfiles\Prod_PublishProfile.pubxml" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\fonts\" />
    <Folder Include="wwwroot\images\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
    <PackageReference Include="Blazored.SessionStorage" Version="2.3.0" />
    <PackageReference Include="MudBlazor" Version="6.1.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MarketplaceBetter.Domain\MarketplaceBetter.Domain.csproj" />
    <ProjectReference Include="..\MarketplaceBetter.Infrastructure\MarketplaceBetter.Infrastructure.csproj" />
    <ProjectReference Include="..\MarketplaceBetter.Services\MarketplaceBetter.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="Pages\Catalog\CopyAndMedia\PhotoUpload\UploadPhotos.razor">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
  </ItemGroup>

</Project>
