CREATE TABLE [dbo].[FulfilledShipment]
(
	[Id]					BIGINT						NOT NULL	IDENTITY,
	[AmazonOrderId]			NVARCHAR (255)				NOT NULL,
	[ShipmentItemId]		NVARCHAR (255)				NOT NULL,
	[AmazonOrderItemId]		NVARCHAR (255)				NOT NULL,
	[PaymentsDate]			DATETIME2					NOT NULL,
	[MerchantSku]			NVARCHAR (255)				NOT NULL,
	[Title]					NVARCHAR (255)				NOT NULL,
	[DispatchedQuantity]	INT							NOT NULL,
	[CurrencyId]			BIGINT						NOT NULL,
	[ItemPrice]				DECIMAL	(19,2)				NOT NULL,
	[ItemTax]				DECIMAL	(19,2)				NOT NULL,
	[DeliveryPrice]			DECIMAL	(19,2)				NOT NULL,
	[DeliveryTax]			DECIMAL	(19,2)				NOT NULL,
	[GiftWrapPrice]			DECIMAL	(19,2)				NOT NULL,
	[GiftWrappingTax]		DECIMAL	(19,2)				NOT NULL,
	[ItemPromoDiscount]		DECIMAL	(19,2)				NOT NULL,
	[ShipmentPromoDiscount]	DECIMAL	(19,2)				NOT NULL,
	[RecipientName]			NVARCHAR (255)				NOT NULL,
	[DeliveryAddress1]		NVARCHAR (255)				NOT NULL,
	[DeliveryAddress2]		NVARCHAR (255)				NOT NULL,
	[DeliveryAddress3]		NVARCHAR (255)				NOT NULL,
	[DeliveryCityTown]		NVARCHAR (255)				NOT NULL,
	[DeliveryCounty]		NVARCHAR (255)				NOT NULL,
	[DeliveryPostcode]		NVARCHAR (255)				NOT NULL,
	[DeliveryCountryId]		BIGINT						NOT NULL,
	[FC]					NVARCHAR (255)				NOT NULL,
	[Error]					NVARCHAR (255)				NULL,
	CONSTRAINT	[PK_FulfilledShipment]					PRIMARY KEY ([Id]),
	CONSTRAINT  [FK_FulfilledShipment_Currency]			FOREIGN KEY ([CurrencyId])	REFERENCES [dbo].[Currency] ([Id]),
	CONSTRAINT  [FK_FulfilledShipment_DeliveryCountry]	FOREIGN KEY ([DeliveryCountryId])	REFERENCES [dbo].[Country] ([Id]),
);
GO